### PR TITLE
add consider_3g_degraded, fix some exceptions, redo self.speed lut

### PR DESCRIPTION
**Pull request by girst**
you've already implemented format_error, i see. 

~~I'm not sure if your `self.speed` is correct, I'll push another commit to this in a few minutes.~~ done

~~your version doesn't run for me currently~~ fixed (exceptions caught)

### CODE REVIEW

**Comment by girst** [comment]
the `self.speed ` lookup table had some value (e.g. 192) which were not in the one from the  link  you provided, so i copied it over. 

where did you get the data for `self.states` from?

also, your handling of 'no modem' was wrong: you loop over all the possible modem numbers, so only if the for loop never finds anything we don't have a modem connected. therefore, we have to set the 'no modem' string before the loop, otherwise we get an exception. 

some of the values in the `data[]` dict might be not available during initialisation; I've put a `try`/`catch` around them. 

lastly, the except block (now line 186) does not fire when no modem is connected, but when something else happens. I do not know when, so could you have a look at this?

**Comment by cyrinux** [comment]
Thanks, 192 I add a random value because I get this one sometime before
connected and get an error. I must find why and how to handle this... If
you have an idea.
I will look for other things, I'm learning I must understand ^^Thx!

**Comment by cyrinux** [comment]
For state for the moment I don't find a doc with value like for speed so I
try to adapt them based on what I see in journalctl -fab while testing

**Review by cyrinux — COMMENTED** [review]
For consider degraded. We can find something what is the max value for the modem. We must introspect dbus then use this value. Not hardcode LTE

**Comment by girst** [comment]
Thanks for explain! 

I#ve fixed the 192 thingy. the speed lut describes a bitmask, meaning for example that if the 14th bit is set, we have 'LTE', and if the 8th is  set we only have '3g'. if we have both bits set, we have 'lte'+'3g' available. `1<<(status['access-technologies'].bit_length()-1)` extracts the highest available network setting, so we don't get values like 192 (which would be 11000000 in binary) and turn them into 128 (10000000)


(sorry, that turned out quite rambly and incomprehensible)

**Review by cyrinux — APPROVED** [review]

**Pull request merged**
